### PR TITLE
(hackday) - Finalising the default PR default message

### PR DESCRIPTION
**Pull request by pmcmaw**
Please ensure that you have completed all of the following steps:

- [ ] Provided your PR with a meaningful title as this will become an entry in the `CHANGELOG.md`
- [ ] Documented your change in the `README.md` if necessary
- [ ] Included tests for your functionality
- [ ] Added a label to categorize your change
- [ ] Confirmed that all tests are passing

This is an example of a great [PR.](https://git.io/fpRgw) For additional information please see our [contributing guidelines](https://puppet.com/docs/puppet/latest/contributing.html). If you are intrigued as to why we label PRs, please check out [this blog post](https://Linktotheblogpost).

Someone from Puppet will review your PR as soon as possible.

**Thank you for taking the time to contribute to our supported modules.**

### CODE REVIEW

**Comment by davidmalloncares** [comment]
- maybe say "Please ensure.."
- change first 'off' to 'of'

**Comment by eimlav** [comment]
Perhaps provide a title example and ensure to specify a ticket or use `(maint)`

**Comment by pmcmaw** [comment]
@eimlav @davidmalloncares how does that final paragraph look? Or is it something specific yous have in mind for examples? If so can you drop me an example of the example you mean please :-)

**Comment by davidmalloncares** [comment]
Do we document how contributors should use 'labels' anywhere? Feels like linking to a bit more info on that could be helpful.

on docs and tests - I don't have a specific example but is there somewhere we could like to for good examples of docs/readme or tests?

**Comment by pmcmaw** [comment]
@davidmalloncares so I have linked a good example of a PR that includes everything you need. As for the labels, there isnt really an example, to be honest, I think it may be self explanatory, however I can start working on a blog post for labelling, then when its published, it could be linked?

**Comment by davidmalloncares** [comment]
@pmcmaw aye its up to you, if labels are pretty clear then maybe we don't need anything, but if it is not that clear then if we refer to them it would be nice to be able to link to more info somewhere

**Pull request closed without merging**
